//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderXTransaksis = new HashSet<OrderXTransaksi>();
        }

        public Order(Menu menu, int quantity)
        {
            this.Menu = menu;
            this.quantity = quantity;
            this.harga_total_per_item = OrderController.hitungHargaOrder(this);
            this.harga_item_xqty = OrderController.hitungHargaOrderxQty(this);
        }

        public int order_id { get; set; }
        public int menu_id { get; set; }
        public int quantity { get; set; }
        public decimal harga_total_per_item { get; set; }

        public decimal harga_item_xqty { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderXTransaksi> OrderXTransaksis { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual OrderMinuman OrderMinuman { get; set; }
    }
}
