//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMinuman : Order
    {
        public OrderMinuman(Menu menu, Size size, Topping topping, bool isBawaTumblr, int qty)
        {
            this.Menu = menu;
            this.Size1 = size;
            this.Topping = topping;
            this.isBawaTumblr = isBawaTumblr;
            this.quantity = qty;

            this.harga_total_per_item = OrderController.hitungHargaOrder(this);
            this.harga_item_xqty = OrderController.hitungHargaOrderxQty(this);
        }

        public int minuman_id { get; set; }
        public string size { get; set; }
        public int topping_id { get; set; }
        public bool isBawaTumblr { get; set; }
    
        public virtual Topping Topping { get; set; }
        public virtual Size Size1 { get; set; }
        public virtual Order Order { get; set; }
    }
}
