//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderXTransaksi
    {
        public int nomor_transaksi { get; set; }
        public System.DateTime tanggal_transaksi { get; set; }
        public int order_id { get; set; }
        public decimal harga_item_qty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Transaksi Transaksi { get; set; }
    }
}
