//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaksi()
        {
            this.OrderXTransaksis = new HashSet<OrderXTransaksi>();
        }
    
        public int nomor_transaksi { get; set; }
        public System.DateTime tanggal_transaksi { get; set; }
        public int id_pelanggan { get; set; }
        public decimal total_harga { get; set; }
        public decimal total_pajak { get; set; }
        public decimal total_bayar { get; set; }
        public Nullable<int> penambahan_point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderXTransaksi> OrderXTransaksis { get; set; }
        public virtual Pelanggan Pelanggan { get; set; }
    }
}
